# Generated by Django 5.2 on 2025-07-02 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friendly_games', '0005_friendlygameresult'),
        ('matches', '0009_alter_matchplayer_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveScoreboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team1_score', models.PositiveIntegerField(default=0, help_text='Live score for team 1/black team')),
                ('team2_score', models.PositiveIntegerField(default=0, help_text='Live score for team 2/white team')),
                ('current_scorekeeper_codename', models.CharField(blank=True, help_text='Codename of current scorekeeper (for authentication)', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Whether live scoring is currently active')),
                ('last_updated_by', models.CharField(blank=True, help_text='Codename of last person to update scores', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('friendly_game', models.OneToOneField(blank=True, help_text='Friendly game this scoreboard tracks', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='live_scoreboard', to='friendly_games.friendlygame')),
                ('tournament_match', models.OneToOneField(blank=True, help_text='Tournament match this scoreboard tracks', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='live_scoreboard', to='matches.match')),
            ],
            options={
                'verbose_name': 'Live Scoreboard',
                'verbose_name_plural': 'Live Scoreboards',
            },
        ),
        migrations.CreateModel(
            name='ScoreUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team1_score', models.PositiveIntegerField(help_text='Team 1 score at time of update')),
                ('team2_score', models.PositiveIntegerField(help_text='Team 2 score at time of update')),
                ('scorekeeper_codename', models.CharField(help_text='Codename of person who made this update', max_length=50)),
                ('update_type', models.CharField(choices=[('increment', 'Score Increment'), ('correction', 'Score Correction'), ('reset', 'Score Reset')], default='increment', help_text='Type of score update', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('scoreboard', models.ForeignKey(help_text='Scoreboard this update belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='score_updates', to='matches.livescoreboard')),
            ],
            options={
                'verbose_name': 'Score Update',
                'verbose_name_plural': 'Score Updates',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ScorekeeperRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rater_codename', models.CharField(help_text='Codename of person giving the rating', max_length=50)),
                ('accuracy_rating', models.PositiveIntegerField(choices=[(1, 'Very Inaccurate'), (2, 'Inaccurate'), (3, 'Somewhat Accurate'), (4, 'Accurate'), (5, 'Very Accurate')], help_text='Rating of scorekeeper accuracy (1-5)')),
                ('feedback', models.TextField(blank=True, help_text='Optional feedback about the live scoring')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scoreboard', models.ForeignKey(help_text='Scoreboard being rated', on_delete=django.db.models.deletion.CASCADE, related_name='scorekeeper_ratings', to='matches.livescoreboard')),
            ],
            options={
                'verbose_name': 'Scorekeeper Rating',
                'verbose_name_plural': 'Scorekeeper Ratings',
                'unique_together': {('scoreboard', 'rater_codename')},
            },
        ),
    ]
