# Generated by Django 5.2 on 2025-09-25 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0010_add_team_match_participant'),
        ('matches', '0010_livescoreboard_scoreupdate_scorekeeperrating'),
    ]

    operations = [
    ]
