# Generated by Django 5.2 on 2025-10-01 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0011_merge_20250925_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammatchparticipant',
            name='position',
            field=models.CharField(choices=[('pointer', 'Pointer'), ('milieu', 'Milieu'), ('tirer', 'Tirer'), ('flex', 'Flex'), ('substitute', 'Substitute')], default='milieu', help_text="Player's position/role in the match", max_length=20),
        ),
    ]
