# Generated by Django 5.2 on 2025-12-03 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0012_update_participant_position_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='time_limit_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Time limit in minutes (optional). Timer starts when both teams activate the match.', null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='timer_expired',
            field=models.BooleanField(default=False, help_text='Whether the time limit has been reached'),
        ),
        migrations.AddField(
            model_name='match',
            name='timer_expired_at',
            field=models.DateTimeField(blank=True, help_text='When the timer expired (if applicable)', null=True),
        ),
    ]
