# Generated by Django 5.2 on 2026-07-18 12:26

import django.db.models.deletion
import pfc_core.media_uploads
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0014_match_add_poule'),
        ('tournaments', '0022_tournamentteam_vs_points_vsencounter_vslineup'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='vs_encounter',
            field=models.ForeignKey(blank=True, help_text='VS Encounter this sub-game belongs to (VS Mode only)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_games', to='tournaments.vsencounter'),
        ),
        migrations.AddField(
            model_name='match',
            name='vs_lineup_team1_locked',
            field=models.BooleanField(default=False, help_text='True when team1 has submitted and locked their lineup for this VS sub-game'),
        ),
        migrations.AddField(
            model_name='match',
            name='vs_lineup_team2_locked',
            field=models.BooleanField(default=False, help_text='True when team2 has submitted and locked their lineup for this VS sub-game'),
        ),
        migrations.AddField(
            model_name='match',
            name='vs_points_value',
            field=models.IntegerField(blank=True, help_text='Points awarded to the winning team for this VS sub-game (e.g. 2 for Tête-à-tête)', null=True),
        ),
        migrations.AlterField(
            model_name='matchresult',
            name='photo_evidence',
            field=models.ImageField(blank=True, null=True, upload_to=pfc_core.media_uploads.match_evidence_photo_path),
        ),
    ]
