# Generated by Django 5.2 on 2026-09-19 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0015_match_vs_encounter_match_vs_lineup_team1_locked_and_more'),
        ('teams', '0011_playerprofile_privacy_boules'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='starting_team',
            field=models.ForeignKey(blank=True, help_text='Team randomly selected to start this Match', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_starting', to='teams.team'),
        ),
    ]
