# Generated by Django 5.2 on 2026-09-23 00:30

import django.db.models.deletion
from django.db import migrations, models


def preflight_live_court_conflicts(apps, schema_editor):
    Match = apps.get_model('matches', 'Match')
    conflicts = list(
        Match.objects.filter(
            court__isnull=False,
            status__in=('active', 'waiting_validation'),
        )
        .values('court_id')
        .annotate(total=models.Count('id'))
        .filter(total__gt=1)
        .order_by('court_id')[:10]
    )
    if conflicts:
        raise RuntimeError(
            'Cannot add one_live_match_per_court while live Court conflicts '
            f'exist: {conflicts}. Resolve them explicitly before migrating.'
        )


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0011_courtcomplex_gps_coordinates'),
        ('matches', '0016_match_starting_team'),
        ('teams', '0011_playerprofile_privacy_boules'),
        ('tournaments', '0033_tournament_lifecycle_guards'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchLifecycleTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RunPython(preflight_live_court_conflicts, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ('active', 'waiting_validation'))), fields=('court',), name='one_live_match_per_court'),
        ),
        migrations.AddField(
            model_name='matchlifecycletransition',
            name='match',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lifecycle_transition', to='matches.match'),
        ),
        migrations.AddField(
            model_name='matchlifecycletransition',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_lifecycle_transitions', to='tournaments.tournament'),
        ),
        migrations.AddIndex(
            model_name='matchlifecycletransition',
            index=models.Index(fields=['tournament', 'status'], name='match_transition_status_idx'),
        ),
    ]
