# Generated by Django 5.2 on 2025-10-01 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0006_subteam_subteamplayerassignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerprofile',
            name='preferred_position',
            field=models.CharField(blank=True, choices=[('pointer', 'Pointer'), ('milieu', 'Milieu'), ('tirer', 'Tirer'), ('flex', 'Flex')], default='milieu', max_length=20, null=True),
        ),
    ]
