# Generated by Django 5.2 on 2026-06-07 08:00

import pfc_core.media_uploads
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0008_team_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerprofile',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Active profiles are included in ratings, PFC Market, and ranking. Admins can deactivate a profile without deleting it.'),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=pfc_core.media_uploads.player_profile_picture_path),
        ),
        migrations.AlterField(
            model_name='teamprofile',
            name='logo_svg',
            field=models.FileField(blank=True, help_text='Team logo in SVG format (vector graphics, scalable)', null=True, upload_to=pfc_core.media_uploads.team_logo_path),
        ),
        migrations.AlterField(
            model_name='teamprofile',
            name='team_photo_jpg',
            field=models.ImageField(blank=True, help_text='Team photo in JPG format (group photo, team picture)', null=True, upload_to=pfc_core.media_uploads.team_photo_path),
        ),
    ]
