# Generated by Django 5.2 on 2026-06-24 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0009_playerprofile_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='is_tournament_temp',
            field=models.BooleanField(default=False, help_text='True for auto-generated tournament-scoped temporary teams (Mêlée, Tête-à-tête). Hidden from public team list.'),
        ),
    ]
