# Generated by Django 5.2 on 2025-08-31 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courts', '0008_rename_is_active_to_is_available'),
        ('tournaments', '0010_add_original_team_to_melee_player'),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('is_free', models.BooleanField(default=False)),
                ('requires_voucher', models.BooleanField(default=True)),
                ('max_doubles_players', models.IntegerField(default=12)),
                ('max_triples_players', models.IntegerField(default=18)),
                ('tournament_type', models.CharField(choices=[('swiss', 'Swiss'), ('partial_robin', 'Partial Round Robin'), ('round_robin', 'Round Robin')], max_length=20)),
                ('num_rounds', models.IntegerField(default=3)),
                ('matches_per_team', models.IntegerField(default=3)),
                ('draft_type', models.CharField(choices=[('balance', 'Balance Draft'), ('snake', 'Snake Draft'), ('random', 'Random Draft')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VoucherCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('is_used', models.BooleanField(default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simple_creator.tournamentscenario')),
                ('used_for_tournament', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tournaments.tournament')),
            ],
        ),
        migrations.CreateModel(
            name='SimpleTournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format_type', models.CharField(choices=[('doubles', 'Doubles'), ('triples', 'Triples')], max_length=10)),
                ('auto_start_date', models.DateTimeField()),
                ('auto_end_date', models.DateTimeField()),
                ('team_pins_generated', models.BooleanField(default=False)),
                ('is_completed', models.BooleanField(default=False)),
                ('badges_assigned', models.BooleanField(default=False)),
                ('players_restored', models.BooleanField(default=False)),
                ('mele_teams_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('court_complex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courts.courtcomplex')),
                ('tournament', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tournaments.tournament')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simple_creator.tournamentscenario')),
                ('voucher_used', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='simple_creator.vouchercode')),
            ],
        ),
    ]
