# Generated by Django 5.2 on 2025-09-07 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_creator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentscenario',
            name='tournament_type',
            field=models.CharField(choices=[('swiss', 'Swiss'), ('round_robin', 'Round Robin')], max_length=20),
        ),
    ]
