# Generated by Django 5.2 on 2025-09-07 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0008_rename_is_active_to_is_available'),
        ('simple_creator', '0003_add_virtual_courts_support'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simpletournament',
            name='court_complex',
            field=models.ForeignKey(blank=True, help_text='Real court complex (for advanced tournaments)', null=True, on_delete=django.db.models.deletion.CASCADE, to='courts.courtcomplex'),
        ),
        migrations.AlterField(
            model_name='simpletournament',
            name='uses_virtual_courts',
            field=models.BooleanField(default=True, help_text='Whether this tournament uses virtual courts'),
        ),
    ]
