# Generated by Django 5.2 on 2025-11-30 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0008_rename_is_active_to_is_available'),
        ('simple_creator', '0004_alter_simpletournament_court_complex_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentscenario',
            name='default_court_complex',
            field=models.ForeignKey(blank=True, help_text='Default court complex to use for tournaments with this scenario', null=True, on_delete=django.db.models.deletion.SET_NULL, to='courts.courtcomplex'),
        ),
    ]
