# Generated by Django 5.2 on 2025-11-30 09:27

import django.db.models.deletion
from django.db import migrations, models


def set_default_court_complex(apps, schema_editor):
    """
    Set default court complex for existing TournamentScenario records.
    Uses the first available CourtComplex, or leaves null if none exist.
    """
    TournamentScenario = apps.get_model('simple_creator', 'TournamentScenario')
    CourtComplex = apps.get_model('courts', 'CourtComplex')
    
    # Get first available court complex
    first_court = CourtComplex.objects.first()
    
    if first_court:
        # Update all existing scenarios without a court complex
        TournamentScenario.objects.filter(default_court_complex__isnull=True).update(
            default_court_complex=first_court
        )


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0008_rename_is_active_to_is_available'),
        ('simple_creator', '0005_tournamentscenario_default_court_complex'),
    ]

    operations = [
        # First, populate existing records with a default value
        migrations.RunPython(
            set_default_court_complex,
            reverse_code=migrations.RunPython.noop
        ),
        # Then make the field required
        migrations.AlterField(
            model_name='tournamentscenario',
            name='default_court_complex',
            field=models.ForeignKey(
                help_text='Court complex to use for tournaments with this scenario (required)',
                on_delete=django.db.models.deletion.PROTECT,
                to='courts.courtcomplex'
            ),
        ),
    ]
