# Generated by Django 5.2 on 2025-12-03 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_creator', '0006_alter_tournamentscenario_default_court_complex'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentscenario',
            name='default_time_limit_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Default time limit in minutes for all matches in this scenario (optional)', null=True),
        ),
        migrations.AlterField(
            model_name='tournamentscenario',
            name='tournament_type',
            field=models.CharField(choices=[('swiss', 'Swiss'), ('round_robin', 'Round Robin'), ('knockout', 'Knockout'), ('wtf', 'WTF (πετΑ Index)'), ('smart_swiss', 'Smart Swiss')], max_length=20),
        ),
    ]
