# Generated by Django 5.2 on 2025-12-03 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_creator', '0007_add_timer_and_algorithms'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScenarioStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_number', models.PositiveIntegerField()),
                ('name', models.CharField(blank=True, max_length=100)),
                ('format', models.CharField(choices=[('swiss', 'Swiss System'), ('smart_swiss', 'Smart Swiss System'), ('wtf', 'WTF (πετΑ Index)'), ('poule', 'Poules/Groups'), ('knockout', 'Knockout'), ('round_robin', 'Round Robin')], max_length=20)),
                ('num_qualifiers', models.PositiveIntegerField(help_text='Number of teams advancing FROM this stage (0 for final stage)')),
                ('num_rounds_in_stage', models.PositiveIntegerField(default=1, help_text='Number of rounds within this stage (e.g., for Swiss)')),
                ('num_matches_per_team', models.PositiveIntegerField(blank=True, help_text='Number of matches per team for Incomplete Round Robin format (leave blank for full Round Robin)', null=True)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenario_stages', to='simple_creator.tournamentscenario')),
            ],
            options={
                'ordering': ['stage_number'],
                'unique_together': {('scenario', 'stage_number')},
            },
        ),
    ]
