# Generated by Django 5.2 on 2026-05-20 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_creator', '0008_add_scenario_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentscenario',
            name='pregame_countdown_minutes',
            field=models.PositiveSmallIntegerField(blank=True, help_text="Duration in minutes of the pre-game 'Find Your Court' countdown. Leave blank to use the system default (3 minutes).", null=True),
        ),
        migrations.AddField(
            model_name='tournamentscenario',
            name='scenario_mode',
            field=models.CharField(choices=[('melee', 'Mêlée (individual registration, dynamic teams)'), ('super_melee', 'Super Mêlée (Mêlée + player shuffle after each round)'), ('team', 'Normal Team Tournament (existing team registration)')], default='melee', help_text='Type of tournament this scenario creates', max_length=20),
        ),
    ]
