# Generated by Django 5.2 on 2026-06-24 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_creator', '0009_add_scenario_mode_and_pregame_countdown'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentscenario',
            name='max_singles_players',
            field=models.IntegerField(default=24),
        ),
        migrations.AlterField(
            model_name='simpletournament',
            name='format_type',
            field=models.CharField(choices=[('singles', 'Singles / Tête-à-tête'), ('doubles', 'Doubles'), ('triples', 'Triples')], max_length=10),
        ),
    ]
