# Generated by Django 5.2 on 2026-07-14 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_creator', '0010_add_singles_format_and_max_singles_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentscenario',
            name='supports_doubles',
            field=models.BooleanField(default=True, help_text='Scenario supports Doubles (2-player entries)'),
        ),
        migrations.AddField(
            model_name='tournamentscenario',
            name='supports_singles',
            field=models.BooleanField(default=False, help_text='Scenario supports Singles / Tête-à-tête (1-player individual entries, temporary teams)'),
        ),
        migrations.AddField(
            model_name='tournamentscenario',
            name='supports_triples',
            field=models.BooleanField(default=True, help_text='Scenario supports Triples (3-player entries)'),
        ),
    ]
