# Generated by Django 5.2 on 2026-07-18 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_creator', '0011_add_scenario_format_support_flags'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentscenario',
            name='vs_config',
            field=models.JSONField(blank=True, default=None, help_text='VS Mode game composition and point values. Example: {"games": [{"format": "tete_a_tete", "count": 6, "points_per_win": 2}, {"format": "doublets", "count": 3, "points_per_win": 3}, {"format": "triplets", "count": 2, "points_per_win": 5}]}', null=True),
        ),
        migrations.AlterField(
            model_name='tournamentscenario',
            name='scenario_mode',
            field=models.CharField(choices=[('melee', 'Mêlée (individual registration, dynamic teams)'), ('super_melee', 'Super Mêlée (Mêlée + player shuffle after each round)'), ('team', 'Normal Team Tournament (existing team registration)'), ('vs_mode', 'VS Mode (Team vs Team, multi-format encounter)')], default='melee', help_text='Type of tournament this scenario creates', max_length=20),
        ),
    ]
