# Generated by Django 5.2 on 2026-08-13 15:24

import django.db.models.deletion
from django.db import migrations, models


def normalize_vs_scenarios(apps, schema_editor):
    """Move existing VS Scenarios off generic Knockout metadata safely."""
    TournamentScenario = apps.get_model('simple_creator', 'TournamentScenario')
    TournamentScenario.objects.filter(scenario_mode='vs_mode').update(
        tournament_type='independent_games',
        supports_singles=True,
        supports_doubles=True,
        supports_triples=True,
    )


def noop_reverse(apps, schema_editor):
    # Do not restore misleading algorithm or format values on rollback.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('cert_ratings', '0001_initial'),
        ('simple_creator', '0012_tournamentscenario_vs_config_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentscenario',
            name='certifying_entity',
            field=models.ForeignKey(blank=True, help_text='Optional Certifying Entity for tournaments created from this Scenario.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scenarios', to='cert_ratings.certifyingentity'),
        ),
        migrations.AddField(
            model_name='tournamentscenario',
            name='vs_default_num_matches',
            field=models.PositiveIntegerField(default=11, help_text='Default Number of Games for an Independent Games / VS Scenario. The creator may choose a different value of at least one game.'),
        ),
        migrations.AlterField(
            model_name='tournamentscenario',
            name='tournament_type',
            field=models.CharField(choices=[('swiss', 'Swiss'), ('round_robin', 'Round Robin'), ('knockout', 'Knockout'), ('wtf', 'WTF (πετΑ Index)'), ('smart_swiss', 'Smart Swiss'), ('independent_games', 'Independent Games (VS only)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='tournamentscenario',
            name='vs_config',
            field=models.JSONField(blank=True, default=None, help_text='Legacy fixed VS composition retained for historical records. New VS scenarios use Independent Games and the Number of Games setting instead.', null=True),
        ),
        migrations.RunPython(normalize_vs_scenarios, noop_reverse),
    ]
