# Generated by Django 5.2 on 2026-08-13 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_creator', '0013_tournamentscenario_certifying_entity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simpletournament',
            name='format_type',
            field=models.CharField(choices=[('singles', 'Singles / Tête-à-tête'), ('doubles', 'Doubles'), ('triples', 'Triples'), ('vs', 'VS / Independent Games')], max_length=20),
        ),
    ]
