# Generated by Django 5.2 on 2026-08-13 17:05

import pfc_core.media_uploads
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_creator', '0014_alter_simpletournament_format_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentscenario',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional image displayed on this Scenario card in the Simple Tournament Creator.', null=True, upload_to=pfc_core.media_uploads.scenario_image_path),
        ),
    ]
