# Generated by Django 5.2 on 2026-08-16 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_creator', '0015_tournamentscenario_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentScenarioTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(choices=[('en', 'English'), ('el', 'Greek / Ελληνικά')], max_length=10)),
                ('display_name', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='display_translations', to='simple_creator.tournamentscenario')),
            ],
            options={
                'ordering': ['language_code'],
                'constraints': [models.UniqueConstraint(fields=('scenario', 'language_code'), name='unique_scenario_display_translation_language')],
            },
        ),
    ]
