# Generated by Django 5.2 on 2026-09-19 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_creator', '0016_scenario_display_translations'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScenarioTournamentSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateField()),
                ('last_sequence', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_title_sequences', to='simple_creator.tournamentscenario')),
            ],
            options={
                'verbose_name': 'Scenario tournament title sequence',
                'verbose_name_plural': 'Scenario tournament title sequences',
                'ordering': ['scenario_id', 'event_date'],
                'constraints': [models.UniqueConstraint(fields=('scenario', 'event_date'), name='unique_scenario_tournament_title_sequence_date')],
            },
        ),
    ]
