# Generated by Django 5.2 on 2026-10-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_creator', '0017_scenario_tournament_title_sequences'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentscenario',
            name='lineup_selection_seconds',
            field=models.PositiveIntegerField(
                default=0,
                help_text=(
                    'Lineup / position selection window in seconds for each newly '
                    'generated Round. Zero freezes valid default lineups immediately.'
                ),
            ),
        ),
    ]
