# Generated by Django 5.2 on 2026-04-11 06:13

import pfc_core.media_uploads
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0008_rename_is_active_to_is_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courtcomplexphoto',
            name='image',
            field=models.ImageField(help_text='Photo of the court complex', upload_to=pfc_core.media_uploads.court_complex_photo_path),
        ),
    ]
