# Generated by Django 5.2 on 2025-08-24 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friendly_games', '0005_friendlygameresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendlygame',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('WAITING_FOR_PLAYERS', 'Waiting for Players'), ('READY', 'Ready to Play'), ('ACTIVE', 'In Progress'), ('PENDING_VALIDATION', 'Pending Validation'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], default='WAITING_FOR_PLAYERS', max_length=20),
        ),
    ]
