# Generated by Django 5.2 on 2026-03-17 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0008_rename_is_active_to_is_available'),
        ('friendly_games', '0006_ensure_codename_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendlygame',
            name='court',
            field=models.ForeignKey(blank=True, help_text='Specific court where this game is played', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='friendly_games', to='courts.court'),
        ),
        migrations.AddField(
            model_name='friendlygame',
            name='court_complex',
            field=models.ForeignKey(blank=True, help_text='Court complex where this game is played', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='friendly_games', to='courts.courtcomplex'),
        ),
        migrations.AddField(
            model_name='friendlygame',
            name='is_timed',
            field=models.BooleanField(default=False, help_text='Whether this game has a time limit'),
        ),
        migrations.AddField(
            model_name='friendlygame',
            name='time_limit_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Time limit in minutes (only used when is_timed=True)', null=True),
        ),
        migrations.AddField(
            model_name='friendlygame',
            name='timer_expired',
            field=models.BooleanField(default=False, help_text='Whether the time limit has been reached'),
        ),
        migrations.AddField(
            model_name='friendlygame',
            name='timer_started_at',
            field=models.DateTimeField(blank=True, help_text='When the timer was started (game activated)', null=True),
        ),
    ]
