# Generated by Django 5.2 on 2026-03-17 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0007_update_position_choices'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Email OTP',
                'verbose_name_plural': 'Email OTPs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PFCUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('provider', models.CharField(choices=[('google', 'Google'), ('email', 'Email OTP')], help_text='Primary auth provider used to create this account', max_length=10)),
                ('google_sub', models.CharField(blank=True, help_text="Google 'sub' (subject) ID — stable unique identifier from Google", max_length=128, null=True, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=150)),
                ('avatar_url', models.URLField(blank=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('legacy_codename_linked', models.BooleanField(default=False, help_text='True if user linked an existing player via legacy codename')),
                ('legacy_link_skipped', models.BooleanField(default=False, help_text='True if user explicitly skipped the legacy link step')),
                ('player', models.OneToOneField(blank=True, help_text='Linked PFC Player record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pfc_user', to='teams.player')),
            ],
            options={
                'verbose_name': 'PFC User',
                'verbose_name_plural': 'PFC Users',
                'ordering': ['-created_at'],
            },
        ),
    ]
