# Generated by Django 5.2 on 2025-08-24 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0006_alter_bracket_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='round',
            unique_together={('tournament', 'stage', 'number_in_stage')},
        ),
        migrations.CreateModel(
            name='AutomationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournament_id', models.IntegerField()),
                ('event_type', models.CharField(choices=[('automation_start', 'Automation Start'), ('decision', 'Decision Point'), ('action', 'Action Taken'), ('error', 'Error Occurred'), ('success', 'Success'), ('status_change', 'Status Change')], max_length=20)),
                ('message', models.TextField()),
                ('details', models.TextField(blank=True)),
                ('reasoning', models.TextField(blank=True)),
                ('context', models.TextField(blank=True)),
                ('trigger_type', models.CharField(blank=True, max_length=50)),
                ('data', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['tournament_id', '-timestamp'], name='tournaments_tournam_846218_idx'), models.Index(fields=['event_type', '-timestamp'], name='tournaments_event_t_8d998d_idx')],
            },
        ),
    ]
