# Generated by Django 5.2 on 2025-08-24 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0006_subteam_subteamplayerassignment'),
        ('tournaments', '0007_alter_round_unique_together_automationlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='is_melee',
            field=models.BooleanField(default=False, help_text='Enable Mêlée mode for individual player registration'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='melee_format',
            field=models.CharField(blank=True, choices=[('doublets', 'Doublettes (2 players)'), ('triplets', 'Triplettes (3 players)')], help_text='Team format for Mêlée mode (only used when is_melee=True)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='melee_teams_generated',
            field=models.BooleanField(default=False, help_text='Whether Mêlée teams have been automatically generated'),
        ),
        migrations.CreateModel(
            name='MeleePlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_team', models.ForeignKey(blank=True, help_text='Auto-generated team this player was assigned to', null=True, on_delete=django.db.models.deletion.SET_NULL, to='teams.team')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.player')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='melee_players', to='tournaments.tournament')),
            ],
            options={
                'verbose_name': 'Mêlée Player',
                'verbose_name_plural': 'Mêlée Players',
                'unique_together': {('tournament', 'player')},
            },
        ),
    ]
