# Generated by Django 5.2 on 2025-08-24 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0008_add_melee_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='num_matches_per_team',
            field=models.PositiveIntegerField(blank=True, help_text='Number of matches per team for Incomplete Round Robin format (leave blank for full Round Robin)', null=True),
        ),
    ]
