# Generated by Django 5.2 on 2025-08-26 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0006_subteam_subteamplayerassignment'),
        ('tournaments', '0009_add_incomplete_round_robin'),
    ]

    operations = [
        migrations.AddField(
            model_name='meleeplayer',
            name='original_team',
            field=models.ForeignKey(blank=True, help_text='Original team before mêlée assignment for restoration', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='original_melee_players', to='teams.team'),
        ),
        migrations.AlterField(
            model_name='meleeplayer',
            name='assigned_team',
            field=models.ForeignKey(blank=True, help_text='Auto-generated team this player was assigned to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_melee_players', to='teams.team'),
        ),
    ]
