# Generated by Django 5.2 on 2025-09-02 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0010_add_original_team_to_melee_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='max_participants',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum number of individual players allowed to register (for Mêlée tournaments)', null=True),
        ),
    ]
