# Generated by Django 5.2 on 2025-09-05 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0011_tournament_max_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='banner_alt_text',
            field=models.CharField(blank=True, help_text='Alternative text for banner image (for accessibility)', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='banner_enabled',
            field=models.BooleanField(default=False, help_text='Enable/disable banner display on tournament overview page'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='banner_image',
            field=models.ImageField(blank=True, help_text='Banner image for advertisement (max 2MB, jpg/png/svg)', null=True, upload_to='tournament_banners/'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='banner_target_url',
            field=models.URLField(blank=True, help_text='Target URL where banner click should redirect (must be http/https)', null=True),
        ),
    ]
