# Generated by Django 5.2 on 2025-10-09 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0012_tournament_banner_alt_text_tournament_banner_enabled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='format',
            field=models.CharField(choices=[('round_robin', 'Round Robin'), ('knockout', 'Knockout'), ('swiss', 'Swiss System'), ('smart_swiss', 'Smart Swiss System'), ('multi_stage', 'Multi-Stage')], default='knockout', max_length=20),
        ),
    ]
