# Generated by Django 5.2 on 2025-10-09 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0013_alter_tournament_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='format',
            field=models.CharField(choices=[('swiss', 'Swiss System'), ('smart_swiss', 'Smart Swiss System'), ('poule', 'Poules/Groups'), ('knockout', 'Knockout'), ('round_robin', 'Round Robin')], max_length=20),
        ),
    ]
