# Generated by Django 5.2 on 2025-10-15 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0014_alter_stage_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='format',
            field=models.CharField(choices=[('swiss', 'Swiss System'), ('smart_swiss', 'Smart Swiss System'), ('wtf', 'WTF (πετΑ Index)'), ('poule', 'Poules/Groups'), ('knockout', 'Knockout'), ('round_robin', 'Round Robin')], max_length=20),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='format',
            field=models.CharField(choices=[('round_robin', 'Round Robin'), ('knockout', 'Knockout'), ('swiss', 'Swiss System'), ('smart_swiss', 'Smart Swiss System'), ('wtf', 'WTF (πετΑ Index)'), ('multi_stage', 'Multi-Stage')], default='knockout', max_length=20),
        ),
    ]
