# Generated by Django 5.2 on 2025-12-03 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0015_add_wtf_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='default_time_limit_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Default time limit in minutes for all matches in this tournament (optional). Applied automatically when matches are created.', null=True),
        ),
    ]
