# Generated by Django 5.2 on 2025-12-09 09:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0007_update_position_choices'),
        ('tournaments', '0016_add_default_time_limit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='shuffle_players_after_round',
            field=models.BooleanField(default=False, help_text='Automatically shuffle players between mêlée teams after each round completes'),
        ),
        migrations.CreateModel(
            name='MeleeShuffleHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveIntegerField(help_text='Round number after which shuffling occurred')),
                ('shuffle_type', models.CharField(choices=[('automatic', 'Automatic (after round completion)'), ('manual', 'Manual (admin triggered)')], default='manual', help_text='How the shuffle was triggered', max_length=20)),
                ('shuffled_at', models.DateTimeField(auto_now_add=True, help_text='When the shuffle occurred')),
                ('players_shuffled', models.PositiveIntegerField(default=0, help_text='Number of players that were shuffled')),
                ('notes', models.TextField(blank=True, help_text='Optional notes about the shuffle')),
                ('shuffled_by', models.ForeignKey(blank=True, help_text='Admin user who triggered the shuffle (for manual shuffles)', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tournament', models.ForeignKey(help_text='The tournament where shuffling occurred', on_delete=django.db.models.deletion.CASCADE, related_name='shuffle_history', to='tournaments.tournament')),
            ],
            options={
                'verbose_name_plural': 'Mêlée shuffle histories',
                'ordering': ['-shuffled_at'],
            },
        ),
        migrations.CreateModel(
            name='MeleePartnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveIntegerField(help_text='Round number when this partnership was formed')),
                ('team_name', models.CharField(help_text='Name of the mêlée team they were on together', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this partnership was recorded')),
                ('player1', models.ForeignKey(help_text='First player in the partnership', on_delete=django.db.models.deletion.CASCADE, related_name='partnerships_as_player1', to='teams.player')),
                ('player2', models.ForeignKey(help_text='Second player in the partnership', on_delete=django.db.models.deletion.CASCADE, related_name='partnerships_as_player2', to='teams.player')),
                ('tournament', models.ForeignKey(help_text='The tournament where this partnership occurred', on_delete=django.db.models.deletion.CASCADE, related_name='melee_partnerships', to='tournaments.tournament')),
            ],
            options={
                'ordering': ['tournament', 'round_number', 'team_name'],
                'indexes': [models.Index(fields=['tournament', 'round_number'], name='tournaments_tournam_d47812_idx'), models.Index(fields=['player1', 'player2'], name='tournaments_player1_b02a03_idx')],
                'unique_together': {('tournament', 'round_number', 'player1', 'player2')},
            },
        ),
    ]
