# Generated by Django 5.2 on 2025-12-19 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0007_update_position_choices'),
        ('tournaments', '0017_tournament_shuffle_players_after_round_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeleePlayerStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_rating', models.FloatField(default=1000.0, help_text="Player's PFC rating when tournament started")),
                ('wins', models.PositiveIntegerField(default=0, help_text='Number of matches won (team victories)')),
                ('losses', models.PositiveIntegerField(default=0, help_text='Number of matches lost (team defeats)')),
                ('matches_played', models.PositiveIntegerField(default=0, help_text='Total matches played in this tournament')),
                ('points_scored', models.PositiveIntegerField(default=0, help_text='Total points scored across all matches')),
                ('points_against', models.PositiveIntegerField(default=0, help_text='Total points conceded across all matches')),
                ('current_streak', models.IntegerField(default=0, help_text='Current win/loss streak (positive=wins, negative=losses)')),
                ('best_performance', models.PositiveIntegerField(default=0, help_text='Best consecutive wins achieved in this tournament')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When stats tracking started')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last time stats were updated')),
                ('player', models.ForeignKey(help_text='The player', on_delete=django.db.models.deletion.CASCADE, related_name='melee_stats', to='teams.player')),
                ('tournament', models.ForeignKey(help_text='The mêlée tournament', on_delete=django.db.models.deletion.CASCADE, related_name='melee_player_stats', to='tournaments.tournament')),
            ],
            options={
                'verbose_name': 'Mêlée Player Statistics',
                'verbose_name_plural': 'Mêlée Player Statistics',
                'ordering': ['-wins'],
                'indexes': [models.Index(fields=['tournament', '-wins'], name='tournaments_tournam_d34a94_idx')],
                'unique_together': {('tournament', 'player')},
            },
        ),
    ]
