# Generated by Django 5.2 on 2026-03-28 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0018_meleeplayerstats'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='pregame_countdown_minutes',
            field=models.PositiveSmallIntegerField(default=3, help_text="Duration in minutes of the pre-game 'Find Your Court' countdown shown after match activation (default: 3 minutes)"),
        ),
    ]
