# Generated by Django 5.2 on 2026-06-24 12:41

import pfc_core.media_uploads
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0010_team_is_tournament_temp'),
        ('tournaments', '0020_poule_pouleteam'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='poule',
            name='unique_poule_name_per_stage',
        ),
        migrations.RemoveConstraint(
            model_name='pouleteam',
            name='unique_team_per_poule',
        ),
        migrations.AlterField(
            model_name='tournament',
            name='banner_image',
            field=models.ImageField(blank=True, help_text='Banner image for advertisement (max 2MB, jpg/png/svg)', null=True, upload_to=pfc_core.media_uploads.tournament_banner_path),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='melee_format',
            field=models.CharField(blank=True, choices=[('tete_a_tete', 'Tête-à-tête (1 player — individual)'), ('doublets', 'Doublettes (2 players)'), ('triplets', 'Triplettes (3 players)')], help_text='Team format for Mêlée mode (only used when is_melee=True)', max_length=20, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='poule',
            unique_together={('stage', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='pouleteam',
            unique_together={('poule', 'team')},
        ),
    ]
