# Generated by Django 5.2 on 2026-07-18 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0014_match_add_poule'),
        ('teams', '0010_team_is_tournament_temp'),
        ('tournaments', '0021_add_tete_a_tete_melee_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentteam',
            name='vs_points',
            field=models.IntegerField(default=0, help_text='Total VS Mode points accumulated across all VS encounters'),
        ),
        migrations.CreateModel(
            name='VSEncounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team1_points', models.IntegerField(default=0, help_text='VS points scored by team1 in this encounter')),
                ('team2_points', models.IntegerField(default=0, help_text='VS points scored by team2 in this encounter')),
                ('is_complete', models.BooleanField(default=False, help_text='True when all sub-games in this encounter have been completed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vs_encounters_as_team1', to='teams.team')),
                ('team2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vs_encounters_as_team2', to='teams.team')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vs_encounters', to='tournaments.tournament')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VSLineup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('is_locked', models.BooleanField(default=True, help_text='Once locked, the lineup is final and cannot be changed')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vs_lineups', to='matches.match')),
                ('players', models.ManyToManyField(blank=True, related_name='vs_lineup_participations', to='teams.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vs_lineup_entries', to='teams.team')),
            ],
            options={
                'unique_together': {('match', 'team')},
            },
        ),
    ]
