# Generated by Django 5.2 on 2026-08-13 15:24

from django.db import migrations, models


def normalize_vs_tournaments(apps, schema_editor):
    """Mark historical VS tournaments as Independent Games without deleting data."""
    Tournament = apps.get_model('tournaments', 'Tournament')
    for tournament in Tournament.objects.all().iterator():
        config = tournament.allowed_match_types or {}
        if config.get('vs_mode'):
            tournament.format = 'independent_games'
            tournament.is_multi_stage = False
            tournament.save(update_fields=['format', 'is_multi_stage'])


def noop_reverse(apps, schema_editor):
    # Preserve normalized VS metadata on reversal rather than restoring
    # misleading generic algorithm values.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0023_tournament_certifying_entity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='format',
            field=models.CharField(choices=[('round_robin', 'Round Robin'), ('knockout', 'Knockout'), ('swiss', 'Swiss System'), ('smart_swiss', 'Smart Swiss System'), ('wtf', 'WTF (πετΑ Index)'), ('multi_stage', 'Multi-Stage'), ('independent_games', 'Independent Games (VS)')], default='knockout', max_length=20),
        ),
        migrations.RunPython(normalize_vs_tournaments, noop_reverse),
    ]
