# Generated by Django 5.2 on 2026-08-17 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0024_alter_tournament_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='poule',
            name='max_qualifiers',
            field=models.PositiveIntegerField(default=0, help_text="Maximum teams qualifying from this Pool to the next Stage. Uses this Pool's final standings; 0 means no automatic qualifiers."),
        ),
        migrations.AddField(
            model_name='stage',
            name='progression_message',
            field=models.CharField(blank=True, default='', help_text='Read-only organizer status from the most recent stage progression attempt.', max_length=255),
        ),
    ]
