# Generated by Django 5.2 on 2026-08-20 04:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0011_playerprofile_privacy_boules'),
        ('tournaments', '0025_poule_max_qualifiers_stage_progression_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='max_teams',
            field=models.PositiveIntegerField(blank=True, help_text='Optional maximum number of Teams that may register. Leave blank for no Team limit.', null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='registration_type',
            field=models.CharField(choices=[('free', 'Free'), ('voucher', 'Voucher Required')], default='free', help_text='Whether registrations are free or require a tournament-specific voucher.', max_length=20),
        ),
        migrations.CreateModel(
            name='TournamentRegistrationVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('usage_limit', models.PositiveIntegerField(blank=True, help_text='Optional maximum successful registrations this voucher may authorize.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registration_vouchers', to='tournaments.tournament')),
            ],
            options={
                'ordering': ['tournament', 'code'],
            },
        ),
        migrations.CreateModel(
            name='TournamentRegistrationVoucherRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redeemed_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teams.player')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teams.team')),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='tournaments.tournamentregistrationvoucher')),
            ],
            options={
                'ordering': ['-redeemed_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='tournamentregistrationvoucher',
            constraint=models.UniqueConstraint(fields=('tournament', 'code'), name='unique_tournament_registration_voucher_code'),
        ),
        migrations.AddConstraint(
            model_name='tournamentregistrationvoucherredemption',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('player__isnull', True), ('team__isnull', False)), models.Q(('player__isnull', False), ('team__isnull', True)), _connector='OR'), name='registration_voucher_redemption_has_one_subject'),
        ),
        migrations.AddConstraint(
            model_name='tournamentregistrationvoucherredemption',
            constraint=models.UniqueConstraint(condition=models.Q(('team__isnull', False)), fields=('voucher', 'team'), name='unique_registration_voucher_team_redemption'),
        ),
        migrations.AddConstraint(
            model_name='tournamentregistrationvoucherredemption',
            constraint=models.UniqueConstraint(condition=models.Q(('player__isnull', False)), fields=('voucher', 'player'), name='unique_registration_voucher_player_redemption'),
        ),
    ]
