# Generated by Django 5.2 on 2026-09-17 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0011_playerprofile_privacy_boules'),
        ('tournaments', '0026_tournament_max_teams_tournament_registration_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeleeRoundAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('assigned', 'Assigned to team'), ('bye', 'Bye'), ('waitlisted', 'Waitlisted'), ('withdrawn', 'Withdrawn')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='melee_round_assignments', to='teams.player')),
                ('round', models.ForeignKey(help_text='Concrete tournament round for this assignment state.', on_delete=django.db.models.deletion.CASCADE, related_name='melee_assignments', to='tournaments.round')),
                ('team', models.ForeignKey(blank=True, help_text='Existing temporary tournament team when state is assigned.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='melee_round_assignments', to='teams.team')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='melee_round_assignments', to='tournaments.tournament')),
            ],
            options={
                'verbose_name': 'Mêlée round assignment',
                'verbose_name_plural': 'Mêlée round assignments',
                'ordering': ('round_id', 'state', 'team_id', 'player_id'),
                'indexes': [models.Index(fields=['tournament', 'round', 'team', 'state'], name='melee_round_team_state_idx')],
                'constraints': [models.UniqueConstraint(fields=('tournament', 'round', 'player'), name='unique_melee_round_assignment_player'), models.CheckConstraint(condition=models.Q(models.Q(('state', 'assigned'), ('team__isnull', False)), models.Q(('state__in', ('bye', 'waitlisted', 'withdrawn')), ('team__isnull', True)), _connector='OR'), name='melee_round_assignment_state_team')],
            },
        ),
    ]
