# Generated by Django 5.2 on 2026-09-18 04:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0011_playerprofile_privacy_boules'),
        ('tournaments', '0028_tournament_melee_roster_mode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meleepartnership',
            options={'ordering': ['tournament', 'round_id', 'round_number', 'team_name']},
        ),
        migrations.AlterUniqueTogether(
            name='meleepartnership',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='meleepartnership',
            name='round',
            field=models.ForeignKey(blank=True, help_text='Exact Round for P4 assignment-based partnership history.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='melee_partnerships', to='tournaments.round'),
        ),
        migrations.AddField(
            model_name='meleeshufflehistory',
            name='round',
            field=models.ForeignKey(blank=True, help_text='Exact completed Round for P4 shuffles.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='melee_shuffle_history', to='tournaments.round'),
        ),
        migrations.AddIndex(
            model_name='meleepartnership',
            index=models.Index(fields=['tournament', 'round'], name='tournaments_tournam_c04307_idx'),
        ),
        migrations.AddConstraint(
            model_name='meleepartnership',
            constraint=models.UniqueConstraint(condition=models.Q(('round__isnull', False)), fields=('tournament', 'round', 'player1', 'player2'), name='unique_melee_partnership_exact_round'),
        ),
        migrations.AddConstraint(
            model_name='meleeshufflehistory',
            constraint=models.UniqueConstraint(condition=models.Q(('round__isnull', False)), fields=('tournament', 'round'), name='unique_melee_shuffle_exact_round'),
        ),
    ]
