# Generated by Django 5.2 on 2026-09-19 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0011_playerprofile_privacy_boules'),
        ('tournaments', '0030_tournament_melee_team_algorithm'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeleeRoundTeamBye',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='melee_team_bye', to='tournaments.round')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='melee_round_team_byes', to='teams.team')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='melee_round_team_byes', to='tournaments.tournament')),
            ],
            options={
                'verbose_name': 'Mêlée round team BYE',
                'verbose_name_plural': 'Mêlée round team BYEs',
                'ordering': ('round_id', 'team_id'),
                'indexes': [models.Index(fields=['tournament', 'round', 'team'], name='melee_round_bye_team_idx')],
                'constraints': [models.UniqueConstraint(fields=('tournament', 'round'), name='unique_melee_round_team_bye')],
            },
        ),
    ]
