# Generated by Django 5.2 on 2026-09-19 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0011_playerprofile_privacy_boules'),
        ('tournaments', '0031_snake_draft_individual_byes'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerTournamentAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('award_type', models.CharField(choices=[('medal_gold', 'Gold medal'), ('medal_silver', 'Silver medal'), ('medal_bronze', 'Bronze medal'), ('most_improved', 'Most Improved'), ('win_streak', 'Win Streak'), ('top_scorer', 'Top Scorer'), ('best_win_rate', 'Best Win Rate')], max_length=32)),
                ('historical_team_name', models.CharField(blank=True, max_length=100)),
                ('display_symbol', models.CharField(max_length=4)),
                ('display_title', models.CharField(max_length=160)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('awarded_at', models.DateTimeField(auto_now_add=True)),
                ('historical_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='earned_tournament_achievements', to='teams.team')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_achievements', to='teams.player')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_achievements', to='tournaments.tournament')),
            ],
            options={
                'verbose_name': 'Player tournament achievement',
                'verbose_name_plural': 'Player tournament achievements',
                'ordering': ['-awarded_at', 'award_type'],
                'constraints': [models.UniqueConstraint(fields=('player', 'tournament', 'award_type'), name='unique_player_tournament_achievement')],
            },
        ),
        migrations.CreateModel(
            name='PlayerTournamentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournament_name', models.CharField(max_length=100)),
                ('tournament_date', models.DateField(blank=True, null=True)),
                ('tournament_format', models.CharField(blank=True, max_length=80)),
                ('represented_teams', models.JSONField(blank=True, default=list, help_text='Exact Teams represented in completed tournament Matches.')),
                ('matches_played', models.PositiveIntegerField(default=0)),
                ('wins', models.PositiveIntegerField(default=0)),
                ('losses', models.PositiveIntegerField(default=0)),
                ('points_scored', models.IntegerField(blank=True, null=True)),
                ('points_against', models.IntegerField(blank=True, null=True)),
                ('rating_change', models.DecimalField(blank=True, decimal_places=2, help_text='Recorded PFC rating changes linked to this tournament only.', max_digits=9, null=True)),
                ('finalized_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_history_entries', to='teams.player')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_history_entries', to='tournaments.tournament')),
            ],
            options={
                'verbose_name': 'Player tournament history',
                'verbose_name_plural': 'Player tournament history',
                'ordering': ['-tournament_date', '-tournament_id'],
                'constraints': [models.UniqueConstraint(fields=('player', 'tournament'), name='unique_player_tournament_history_entry')],
            },
        ),
    ]
