# Generated by Django 5.2 on 2026-09-23 00:30

from django.db import migrations, models


def preflight_round_identity_conflicts(apps, schema_editor):
    Round = apps.get_model('tournaments', 'Round')
    overall_conflicts = list(
        Round.objects.values('tournament_id', 'number')
        .annotate(total=models.Count('id'))
        .filter(total__gt=1)
        .order_by('tournament_id', 'number')[:10]
    )
    if overall_conflicts:
        raise RuntimeError(
            'Cannot add Round identity constraint while duplicate overall Round values '
            f'exist: {overall_conflicts}. Resolve them explicitly before migrating.'
        )


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0032_player_tournament_history'),
    ]

    operations = [
        migrations.RunPython(preflight_round_identity_conflicts, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='round',
            constraint=models.UniqueConstraint(fields=('tournament', 'number'), name='unique_tournament_overall_round'),
        ),
    ]
