# Generated by Django 5.2 on 2026-09-24 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0033_tournament_lifecycle_guards'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoundLifecycleTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='round',
            name='lineup_deadline_at',
            field=models.DateTimeField(blank=True, help_text="Authoritative server deadline for this Round's lineup window.", null=True),
        ),
        migrations.AddField(
            model_name='round',
            name='lineups_frozen_at',
            field=models.DateTimeField(blank=True, help_text="When the server froze the Round's final match lineups.", null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='lineup_selection_seconds',
            field=models.PositiveIntegerField(default=0, help_text='Server-authoritative lineup selection window for every newly generated Round. Zero freezes valid default lineups immediately.'),
        ),
        migrations.AddIndex(
            model_name='round',
            index=models.Index(fields=['lineups_frozen_at', 'lineup_deadline_at'], name='round_lineup_dead_idx'),
        ),
        migrations.AddIndex(
            model_name='round',
            index=models.Index(fields=['tournament', 'is_complete', 'number'], name='round_tourn_complete_idx'),
        ),
        migrations.AddField(
            model_name='roundlifecycletransition',
            name='round',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lifecycle_transition', to='tournaments.round'),
        ),
        migrations.AddField(
            model_name='roundlifecycletransition',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='round_lifecycle_transitions', to='tournaments.tournament'),
        ),
        migrations.AddIndex(
            model_name='roundlifecycletransition',
            index=models.Index(fields=['tournament', 'status', 'created_at'], name='round_transition_status_idx'),
        ),
    ]
