# Generated by Django 5.2 on 2025-10-19 20:34

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Unique achievement code (e.g., STREAK_5)', max_length=50, unique=True)),
                ('name', models.CharField(help_text="Display name (e.g., '5 in a row')", max_length=100)),
                ('description', models.TextField(blank=True, help_text='Optional description')),
                ('threshold', models.PositiveIntegerField(help_text='Streak threshold to unlock this achievement')),
                ('icon', models.CharField(blank=True, help_text='CSS icon class or emoji', max_length=50)),
                ('color', models.CharField(default='#FFD700', help_text='Hex color for badge', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['threshold', 'code'],
                'indexes': [models.Index(fields=['threshold'], name='shooting_ac_thresho_c2369d_idx'), models.Index(fields=['is_active'], name='shooting_ac_is_acti_d5dc71_idx')],
            },
        ),
        migrations.CreateModel(
            name='ShotSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mode', models.CharField(choices=[('practice', 'Practice'), ('ingame', 'In-Game')], db_index=True, max_length=20)),
                ('match_id', models.UUIDField(blank=True, help_text="Required if mode is 'ingame'", null=True)),
                ('inning', models.SmallIntegerField(blank=True, help_text='Optional future use for tracking specific innings', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('total_shots', models.PositiveIntegerField(default=0)),
                ('total_hits', models.PositiveIntegerField(default=0)),
                ('best_streak', models.PositiveIntegerField(default=0)),
                ('current_streak', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shot_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ShotEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('idx', models.PositiveIntegerField(help_text='Sequential index within session')),
                ('is_hit', models.BooleanField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='shooting.shotsession')),
            ],
            options={
                'ordering': ['idx'],
            },
        ),
        migrations.CreateModel(
            name='EarnedAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earned_by', to='shooting.achievement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earned_achievements', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earned_achievements', to='shooting.shotsession')),
            ],
            options={
                'ordering': ['-earned_at'],
            },
        ),
        migrations.AddIndex(
            model_name='shotsession',
            index=models.Index(fields=['user', 'mode'], name='shooting_sh_user_id_d053a6_idx'),
        ),
        migrations.AddIndex(
            model_name='shotsession',
            index=models.Index(fields=['match_id'], name='shooting_sh_match_i_1ee551_idx'),
        ),
        migrations.AddIndex(
            model_name='shotsession',
            index=models.Index(fields=['is_active'], name='shooting_sh_is_acti_3ada37_idx'),
        ),
        migrations.AddIndex(
            model_name='shotevent',
            index=models.Index(fields=['session', 'idx'], name='shooting_sh_session_d37d73_idx'),
        ),
        migrations.AddIndex(
            model_name='shotevent',
            index=models.Index(fields=['timestamp'], name='shooting_sh_timesta_3f907d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='shotevent',
            unique_together={('session', 'idx')},
        ),
        migrations.AddIndex(
            model_name='earnedachievement',
            index=models.Index(fields=['user', 'achievement'], name='shooting_ea_user_id_dd6a41_idx'),
        ),
        migrations.AddIndex(
            model_name='earnedachievement',
            index=models.Index(fields=['session'], name='shooting_ea_session_8600d7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='earnedachievement',
            unique_together={('user', 'session', 'achievement')},
        ),
    ]
