# Generated by Django 5.2 on 2025-10-19 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shooting', '0002_seed_achievements'),
    ]

    operations = [
    ]
