# Generated by Django 5.2 on 2026-08-21 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0011_playerprofile_privacy_boules'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebPushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.TextField(unique=True)),
                ('p256dh', models.CharField(max_length=255)),
                ('auth', models.CharField(max_length=255)),
                ('content_encoding', models.CharField(default='aes128gcm', max_length=32)),
                ('locale', models.CharField(default='en', max_length=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='web_push_subscriptions', to='teams.player')),
            ],
            options={
                'verbose_name': 'Web Push subscription',
                'verbose_name_plural': 'Web Push subscriptions',
                'ordering': ['-updated_at'],
            },
        ),
    ]
