# Generated by Django 5.2 on 2025-11-01 11:13

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_codename', models.CharField(db_index=True, max_length=50, unique=True)),
                ('total_sessions', models.PositiveIntegerField(default=0)),
                ('total_shots', models.PositiveIntegerField(default=0)),
                ('total_hits', models.PositiveIntegerField(default=0)),
                ('total_carreaux', models.PositiveIntegerField(default=0)),
                ('total_misses', models.PositiveIntegerField(default=0)),
                ('best_hit_streak', models.PositiveIntegerField(default=0)),
                ('average_session_length', models.DurationField(blank=True, null=True)),
                ('common_miss_position', models.CharField(blank=True, help_text="e.g., 'shots 4-6', 'after shot 10'", max_length=50)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Practice Statistics',
                'db_table': 'practice_statistics',
            },
        ),
        migrations.CreateModel(
            name='PracticeSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('player_codename', models.CharField(db_index=True, help_text='Player codename from PFC system', max_length=50)),
                ('practice_type', models.CharField(choices=[('shooting', 'Shooting')], db_index=True, default='shooting', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('distance', models.CharField(blank=True, help_text="e.g., '6m', '8m', '10m'", max_length=20)),
                ('court', models.CharField(blank=True, help_text='Court identifier', max_length=50)),
                ('terrain', models.CharField(blank=True, help_text='Terrain type', max_length=50)),
                ('notes', models.TextField(blank=True, help_text='Optional session notes')),
                ('total_shots', models.PositiveIntegerField(default=0)),
                ('hits', models.PositiveIntegerField(default=0)),
                ('carreaux', models.PositiveIntegerField(default=0)),
                ('misses', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'db_table': 'practice_sessions',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['player_codename', '-started_at'], name='practice_se_player__761794_idx'), models.Index(fields=['practice_type', '-started_at'], name='practice_se_practic_8f0229_idx')],
            },
        ),
        migrations.CreateModel(
            name='Shot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence_number', models.PositiveIntegerField(help_text='Order in sequence (1, 2, 3, ...)', validators=[django.core.validators.MinValueValidator(1)])),
                ('outcome', models.CharField(choices=[('miss', 'Miss'), ('hit', 'Hit'), ('carreau', 'Carreau')], db_index=True, max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shots', to='practice.practicesession')),
            ],
            options={
                'db_table': 'practice_shots',
                'ordering': ['sequence_number'],
                'indexes': [models.Index(fields=['session', 'sequence_number'], name='practice_sh_session_e32e09_idx'), models.Index(fields=['outcome', 'timestamp'], name='practice_sh_outcome_c2e026_idx')],
                'unique_together': {('session', 'sequence_number')},
            },
        ),
    ]
