# Generated by Django 5.2 on 2025-11-07 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shot',
            name='distance_cm',
            field=models.PositiveIntegerField(blank=True, help_text='Distance from target in centimeters (for pointing practice)', null=True),
        ),
        migrations.AlterField(
            model_name='practicesession',
            name='practice_type',
            field=models.CharField(choices=[('shooting', 'Shooting'), ('pointing', 'Pointing')], db_index=True, default='shooting', max_length=20),
        ),
    ]
