# Generated by Django 5.2 on 2025-11-07 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0002_shot_distance_cm_alter_practicesession_practice_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicesession',
            name='fars',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='practicesession',
            name='goods',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='practicesession',
            name='perfects',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='practicesession',
            name='very_fars',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='shot',
            name='outcome',
            field=models.CharField(choices=[('miss', 'Miss'), ('hit', 'Hit'), ('carreau', 'Carreau'), ('perfect', 'Perfect'), ('good', 'Good'), ('far', 'Far'), ('very_far', 'Very Far')], db_index=True, max_length=10),
        ),
    ]
