# Generated by Django 5.2 on 2025-11-07 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0003_practicesession_fars_practicesession_goods_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicesession',
            name='petit_carreaux',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='practicesession',
            name='petit_perfects',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='shot',
            name='outcome',
            field=models.CharField(choices=[('miss', 'Miss'), ('hit', 'Hit'), ('petit_carreau', 'Petit Carreau'), ('carreau', 'Carreau'), ('perfect', 'Perfect'), ('petit_perfect', 'Petit Perfect'), ('good', 'Good'), ('far', 'Far'), ('very_far', 'Very Far')], db_index=True, max_length=20),
        ),
    ]
