# Generated by Django 5.2 on 2025-11-08 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0004_practicesession_petit_carreaux_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='practicesession',
            name='very_fars',
        ),
        migrations.AddField(
            model_name='practicesession',
            name='fairs',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
