# Generated by Django 5.2 on 2025-11-23 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0005_remove_practicesession_very_fars_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicesession',
            name='sequence_tracking',
            field=models.BooleanField(default=True, help_text='If True, shots must be entered in order. If False, any order is allowed.'),
        ),
        migrations.AlterField(
            model_name='practicesession',
            name='distance',
            field=models.CharField(choices=[('6m', '6 meters'), ('7m', '7 meters'), ('8m', '8 meters'), ('9m', '9 meters'), ('10m', '10 meters')], default='7m', help_text='Fixed throwing distance for the entire session', max_length=3),
        ),
    ]
