# Generated by Django 5.2 on 2026-03-10 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0006_practicesession_sequence_tracking_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practicesession',
            name='distance',
            field=models.CharField(choices=[('6m', '6 meters'), ('7m', '7 meters'), ('8m', '8 meters'), ('9m', '9 meters'), ('10m', '10 meters'), ('ing', 'InG')], default='7m', help_text='Fixed throwing distance for the entire session', max_length=3),
        ),
    ]
