# Generated by Django 5.2 on 2026-05-21 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0007_alter_practicesession_distance'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicesession',
            name='drill_type',
            field=models.CharField(blank=True, default='', help_text='Type of shooting drill for this session (empty = open shot)', max_length=30),
        ),
    ]
