# Generated by Django 5.2 on 2026-05-21 19:09

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0010_courtcomplex_timezone_name'),
        ('practice', '0008_practicesession_drill_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicesession',
            name='court_complex',
            field=models.ForeignKey(blank=True, help_text='Court complex where this session takes place', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='practice_sessions', to='courts.courtcomplex'),
        ),
        migrations.AddField(
            model_name='practicesession',
            name='tdp_score',
            field=models.PositiveIntegerField(default=0, help_text='Total Tir de Précision score (max 100 for a full 20-shot session)'),
        ),
        migrations.AddField(
            model_name='shot',
            name='atelier',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Atelier number (1-5) for Tir de Précision sessions', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='shot',
            name='shot_distance',
            field=models.CharField(blank=True, default='', help_text="Throwing distance for this specific shot (e.g. '6m', '7m') — used in Tir de Précision", max_length=3),
        ),
        migrations.AlterField(
            model_name='practicesession',
            name='distance',
            field=models.CharField(choices=[('6m', '6 meters'), ('7m', '7 meters'), ('8m', '8 meters'), ('9m', '9 meters'), ('10m', '10 meters'), ('ing', 'InG')], default='7m', help_text='Fixed throwing distance for the entire session (not used for Tir de Précision)', max_length=3),
        ),
        migrations.AlterField(
            model_name='shot',
            name='outcome',
            field=models.CharField(choices=[('miss', 'Miss'), ('hit', 'Hit'), ('petit_carreau', 'Petit Carreau'), ('carreau', 'Carreau'), ('tdp_manque', 'Manqué (0 pts)'), ('tdp_touche', 'Touché (1 pt)'), ('tdp_reussi', 'Réussi (3 pts)'), ('tdp_carreau', 'Carreau (5 pts)'), ('tdp_jack_manque', 'Manqué — Jack (0 pts)'), ('tdp_jack_touche', 'Touché — Jack (3 pts)'), ('tdp_jack_reussi', 'Réussi — Jack (5 pts)'), ('perfect', 'Perfect'), ('petit_perfect', 'Petit Perfect'), ('good', 'Good'), ('far', 'Far'), ('very_far', 'Very Far')], db_index=True, max_length=20),
        ),
    ]
