# Generated by Django 5.2 on 2026-06-20 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0009_add_court_complex_and_tdp_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicestatistics',
            name='total_petit_carreaux',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
