# Generated by Django 5.2 on 2025-12-09 10:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billboard', '0004_alter_billboardentry_scheduled_time'),
        ('courts', '0008_rename_is_active_to_is_available'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourtComplexUsageSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('player_count', models.IntegerField(default=0)),
                ('court_complex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_snapshots', to='courts.courtcomplex')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['court_complex', '-timestamp'], name='billboard_c_court_c_656557_idx'), models.Index(fields=['timestamp'], name='billboard_c_timesta_5c3c31_idx')],
            },
        ),
        migrations.CreateModel(
            name='DailyUsageStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('unique_visitors', models.IntegerField(default=0)),
                ('total_check_ins', models.IntegerField(default=0)),
                ('peak_hour', models.IntegerField(blank=True, null=True)),
                ('peak_player_count', models.IntegerField(default=0)),
                ('total_player_hours', models.FloatField(default=0.0)),
                ('average_session_duration_minutes', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('court_complex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_stats', to='courts.courtcomplex')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['court_complex', '-date'], name='billboard_d_court_c_7c2731_idx'), models.Index(fields=['date'], name='billboard_d_date_857fd4_idx')],
                'unique_together': {('court_complex', 'date')},
            },
        ),
        migrations.CreateModel(
            name='HourlyUsageStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('hour', models.IntegerField()),
                ('unique_visitors', models.IntegerField(default=0)),
                ('peak_player_count', models.IntegerField(default=0)),
                ('total_check_ins', models.IntegerField(default=0)),
                ('average_duration_minutes', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('court_complex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hourly_stats', to='courts.courtcomplex')),
            ],
            options={
                'ordering': ['-date', '-hour'],
                'indexes': [models.Index(fields=['court_complex', '-date', '-hour'], name='billboard_h_court_c_273111_idx'), models.Index(fields=['date', 'hour'], name='billboard_h_date_f108ee_idx')],
                'unique_together': {('court_complex', 'date', 'hour')},
            },
        ),
        migrations.CreateModel(
            name='UsageAnalyticsSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(choices=[('week', 'Weekly'), ('month', 'Monthly'), ('year', 'Yearly'), ('all_time', 'All Time')], max_length=20)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('total_unique_visitors', models.IntegerField(default=0)),
                ('total_check_ins', models.IntegerField(default=0)),
                ('average_daily_visitors', models.FloatField(default=0.0)),
                ('busiest_day_of_week', models.IntegerField(blank=True, null=True)),
                ('busiest_hour', models.IntegerField(blank=True, null=True)),
                ('total_player_hours', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('court_complex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_summaries', to='courts.courtcomplex')),
            ],
            options={
                'ordering': ['-period_end'],
                'indexes': [models.Index(fields=['court_complex', 'period_type', '-period_end'], name='billboard_u_court_c_ca89e3_idx')],
                'unique_together': {('court_complex', 'period_type', 'period_start')},
            },
        ),
    ]
