# Generated by Django 5.2 on 2026-04-11 06:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billboard', '0005_courtcomplexusagesnapshot_dailyusagestats_and_more'),
        ('courts', '0009_add_user_presence_prefs'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPresencePrefs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codename', models.CharField(db_index=True, help_text='Player codename (uppercase)', max_length=6, unique=True)),
                ('preferred_time', models.CharField(blank=True, default='', help_text="Most-used time slot, e.g. '10:00'", max_length=5)),
                ('preferred_days', models.CharField(blank=True, default='', help_text='Comma-separated day numbers ordered by frequency', max_length=20)),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_court_complex', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presence_prefs', to='courts.courtcomplex')),
            ],
            options={
                'verbose_name': 'User Presence Prefs',
                'verbose_name_plural': 'User Presence Prefs',
            },
        ),
    ]
