# Generated by Django 5.2 on 2026-06-08 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billboard', '0006_add_user_presence_prefs'),
    ]

    operations = [
        migrations.AddField(
            model_name='billboardentry',
            name='game_ref',
            field=models.CharField(blank=True, db_index=True, help_text="Internal game reference for lifecycle deactivation (e.g. 'friendly:42').", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='billboardentry',
            name='presence_source',
            field=models.CharField(choices=[('manual', 'Manual check-in'), ('friendly_game', 'Friendly game'), ('tournament_match', 'Tournament match')], default='manual', help_text='How this presence entry was created.', max_length=20),
        ),
    ]
