# Generated by Django 5.2 on 2026-06-23 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billboard', '0007_billboardentry_presence_source_game_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='billboardentry',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='When set, the entry is considered expired after this time (used for post-game grace window).', null=True),
        ),
        migrations.AlterField(
            model_name='billboardentry',
            name='presence_source',
            field=models.CharField(choices=[('manual', 'Manual check-in'), ('friendly_game', 'Friendly game'), ('tournament_match', 'Tournament match'), ('post_game', 'Post-game (30 min grace)')], default='manual', help_text='How this presence entry was created.', max_length=20),
        ),
    ]
