# Generated by Django 5.2 on 2026-09-10 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('match_tracking', '0002_trackingauthorization_broadcast_permitted'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='matchtrackingsession',
            new_name='match_track_match_t_37e104_idx',
            old_name='match_track_match_t_579c20_idx',
        ),
    ]
