# Generated by Django 5.2 on 2026-08-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invites', '0002_teambuildsession_include_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='teambuildsession',
            name='registration_voucher_code',
            field=models.CharField(
                blank=True,
                default='',
                help_text='Optional tournament registration voucher supplied when this build session was started.',
                max_length=40,
            ),
        ),
    ]
