# Generated by Django 5.2 on 2026-09-10 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0011_courtcomplex_gps_coordinates'),
        ('invites', '0003_teambuildsession_registration_voucher_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='message',
            field=models.CharField(blank=True, default='', help_text='Optional short note (max 200 chars). Not a conversation thread.', max_length=200),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='play_court',
            field=models.ForeignKey(blank=True, help_text='Proposed court/location', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='play_invitations', to='courts.courtcomplex'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='play_time',
            field=models.DateTimeField(blank=True, help_text='Proposed play time', null=True),
        ),
        migrations.AlterField(
            model_name='teambuildsession',
            name='target_size',
            field=models.PositiveSmallIntegerField(default=3, help_text='Number of players needed to form the team.'),
        ),
    ]
