# Generated by Django 5.2 on 2025-10-13 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboardentry',
            name='buchholz_score',
            field=models.FloatField(default=0.0, help_text='Buchholz tie-breaker score'),
        ),
        migrations.AddField(
            model_name='leaderboardentry',
            name='swiss_points',
            field=models.IntegerField(default=0, help_text='Swiss tournament points (3 per win)'),
        ),
        migrations.AddField(
            model_name='teamstatistics',
            name='swiss_tournaments_played',
            field=models.PositiveIntegerField(default=0, help_text='Number of Swiss tournaments participated in'),
        ),
        migrations.AddField(
            model_name='teamstatistics',
            name='total_swiss_points',
            field=models.IntegerField(default=0, help_text='Total Swiss points across all tournaments'),
        ),
    ]
