# Generated by Django 5.2 on 2026-09-23 00:30

from django.db import migrations, models


def preflight_leaderboard_position_conflicts(apps, schema_editor):
    Entry = apps.get_model('leaderboards', 'LeaderboardEntry')
    conflicts = list(
        Entry.objects.values('leaderboard_id', 'position')
        .annotate(total=models.Count('id'))
        .filter(total__gt=1)
        .order_by('leaderboard_id', 'position')[:10]
    )
    if conflicts:
        raise RuntimeError(
            'Cannot add unique_leaderboard_entry_position while duplicate '
            f'positions exist: {conflicts}. Rebuild or resolve those leaderboards first.'
        )


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboards', '0003_leaderboardentry_stage_reached_tournament_status'),
        ('teams', '0011_playerprofile_privacy_boules'),
    ]

    operations = [
        migrations.RunPython(preflight_leaderboard_position_conflicts, migrations.RunPython.noop),
        migrations.AlterUniqueTogether(
            name='leaderboardentry',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='leaderboardentry',
            constraint=models.UniqueConstraint(fields=('leaderboard', 'team'), name='unique_leaderboard_entry_team'),
        ),
        migrations.AddConstraint(
            model_name='leaderboardentry',
            constraint=models.UniqueConstraint(fields=('leaderboard', 'position'), name='unique_leaderboard_entry_position'),
        ),
    ]
